M48
; DRILL file {KiCad 9.0.7} date 2026-04-28T12:13:44+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-28T12:13:44+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X19.01Y5.315
X24.79Y5.315
T2
X2.3Y13.0
X21.3Y32.6
X72.6Y32.6
X72.6Y2.4
M30
